# docker-compose.yaml
version: '3.7'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: color
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - '127.0.0.1:5455:5432'
    volumes:
      - ./01_create_table.sql:/docker-entrypoint-initdb.d/01_create_table.sql
      - ./02_insert_table.sql:/docker-entrypoint-initdb.d/02_insert_table.sql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    networks:
      - colornetwork
    volumes:
      - .:/app
      - '/app/node_modules'
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    command: ["bash", "-c", "sleep 10 && npm run start:dev"]

networks:
  colornetwork:
    external: true
